all: create clean

create:
	# pdflatex -shell-escap exp1
	pdflatex -shell-escap exp2
	 
clean:
	rm -rf *.aux  *.nav  *.vrb  *.log  *.out *.snm *.toc *.gz *.mtc* *.maf *.fls *.tmp *.bbl *.blg  *.mtc  *.bcf *.xml *.fdb_latexmk plots/*.dep plots/*.dpth plots/*.log plots/*.md5 *.auxlock exp1_fe.pdf

