SET GLOBAL local_infile = 1;

LOAD DATA LOCAL INFILE 'nation.tbl' INTO TABLE `nation` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'region.tbl' INTO TABLE `region` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'part.tbl' INTO TABLE `part` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'supplier.tbl' INTO TABLE `supplier` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE 'partsupp.tbl' INTO TABLE `partsupp` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';	
LOAD DATA LOCAL INFILE 'customer.tbl' INTO TABLE `customer` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';
LOAD DATA LOCAL INFILE 'orders.tbl' INTO TABLE `orders` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n'; 
LOAD DATA LOCAL INFILE 'lineitem.tbl' INTO TABLE `lineitem` FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n'; 

