-- ALTER TABLE region ADD PRIMARY KEY (R_REGIONKEY);
-- ALTER TABLE nation ADD PRIMARY KEY (N_NATIONKEY);
-- ALTER TABLE nation ADD FOREIGN KEY NATION_FK1 (N_REGIONKEY) references region(R_REGIONKEY);
-- ALTER TABLE part ADD PRIMARY KEY (P_PARTKEY);
-- ALTER TABLE supplier ADD PRIMARY KEY (S_SUPPKEY);
-- ALTER TABLE supplier ADD FOREIGN KEY SUPPLIER_FK1 (S_NATIONKEY) references NATION(N_NATIONKEY);
-- ALTER TABLE partsupp ADD PRIMARY KEY (PS_PARTKEY,PS_SUPPKEY);
-- ALTER TABLE customer ADD PRIMARY KEY (C_CUSTKEY);
-- ALTER TABLE customer ADD FOREIGN KEY CUSTOMER_FK1 (C_NATIONKEY) references NATION(N_NATIONKEY);
-- ALTER TABLE lineitem ADD PRIMARY KEY (L_ORDERKEY,L_LINENUMBER);
-- ALTER TABLE partsupp ADD FOREIGN KEY PARTSUPP_FK1 (PS_SUPPKEY) references supplier(S_SUPPKEY);
-- ALTER TABLE partsupp ADD FOREIGN KEY PARTSUPP_FK2 (PS_PARTKEY) references PART(P_PARTKEY);
-- ALTER TABLE orders ADD FOREIGN KEY ORDERS_FK1 (O_CUSTKEY) references customer(C_CUSTKEY);
-- ALTER TABLE lineitem ADD FOREIGN KEY LINEITEM_FK1 (L_ORDERKEY)  references orders(O_ORDERKEY);
-- ALTER TABLE lineitem ADD FOREIGN KEY LINEITEM_FK2 (L_PARTKEY,L_SUPPKEY) references partsupp(PS_PARTKEY, PS_SUPPKEY);


-- indexes on the foreign keys

CREATE INDEX IDX_SUPPLIER_NATION_KEY ON supplier (S_NATIONKEY);

CREATE INDEX IDX_PARTSUPP_PARTKEY ON partsupp (PS_PARTKEY);
CREATE INDEX IDX_PARTSUPP_SUPPKEY ON partsupp (PS_SUPPKEY);

CREATE INDEX IDX_CUSTOMER_NATIONKEY ON customer (C_NATIONKEY);

CREATE INDEX IDX_ORDERS_CUSTKEY ON orders (O_CUSTKEY);

CREATE INDEX IDX_LINEITEM_ORDERKEY ON lineitem (L_ORDERKEY);
CREATE INDEX IDX_LINEITEM_PART_SUPP ON lineitem (L_PARTKEY,L_SUPPKEY);

CREATE INDEX IDX_NATION_REGIONKEY ON nation (N_REGIONKEY);


-- aditional indexes

CREATE INDEX IDX_LINEITEM_SHIPDATE ON lineitem (L_SHIPDATE, L_DISCOUNT, L_QUANTITY);

CREATE INDEX IDX_ORDERS_ORDERDATE ON orders (O_ORDERDATE);

-- analyze tables

-- ANALYZE nation;
-- ANALYZE region;
-- ANALYZE supplier;
-- ANALYZE customer;
-- ANALYZE part;
-- ANALYZE partsupp;
-- ANALYZE orders;
-- ANALYZE lineitem;