create table cmsprovider1(
  averagemedicareallowedamt DOUBLE PRECISION,
  averagemedicarepaymentamt DOUBLE PRECISION,
  averagesubmittedchrgamt DOUBLE PRECISION,
  benedaysrvccnt integer,
  beneuniquecnt integer,
  hcpcscode varchar(5),
  hcpcsdescription varchar(256),
  hcpcsdrugindicator varchar(1),
  linesrvccnt DOUBLE PRECISION,
  medicareparticipationindicator varchar(1),
  npi integer NOT NULL,
  nppescredentials varchar(20),
  nppesentitycode varchar(1),
  nppesprovidercity varchar(28),
  nppesprovidercountry varchar(2),
  nppesprovidergender varchar(1),
  nppesproviderstate varchar(2),
  nppesproviderstreet1 varchar(55),
  nppesproviderstreet2 varchar(55),
  nppesproviderzip integer,
  number_of_records smallint NOT NULL,
  placeofservice varchar(1),
  providertype varchar(43),
  stdevmedicareallowedamt DOUBLE PRECISION,
  stdevmedicarepaymentamt DOUBLE PRECISION,
  stdevsubmittedchrgamt DOUBLE PRECISION
);
