create table mulheresmil1(
  calculation838513981443702785 varchar(8) NOT NULL,
  calculation838513981462429699 varchar(19),
  codigo_diploma_certificado varchar(15),
  cor_da_pele varchar(21),
  data_diploma_certificado timestamp,
  data_pré_matricula date,
  number_of_records smallint NOT NULL,
  chcatalogoguia varchar(4),
  chdaoferta integer NOT NULL,
  chmaxfinanciavel smallint,
  chmaximapermitida smallint NOT NULL,
  chminfinanciavel smallint,
  chminimadocurso smallint NOT NULL,
  comatriculaestudante integer,
  coddaunidadedeensino varchar(5) NOT NULL,
  codibgedaue integer NOT NULL,
  codibgedolocaldaoferta varchar(7) NOT NULL,
  codigodaoferta integer NOT NULL,
  codigodocurso integer NOT NULL,
  comunidadequilombola varchar(89),
  cpf_aluno varchar(11),
  data_de_confirmacao date,
  data_de_nascimento_aluno date,
  datadapublicacao date,
  datadeconclusao varchar(10),
  datadeinicio date,
  datadeprevisaodetermino date,
  desempregado varchar(3),
  dsemail varchar(129),
  dsidentificadorturma varchar(121) NOT NULL,
  dstipobeneficiario varchar(293),
  dtcadastro varchar(26) NOT NULL,
  ead varchar(19) NOT NULL,
  edicaocatalogoguia varchar(14),
  edital varchar(21),
  eixotecnologicocatalogoguia varchar(36),
  eixotecnológico varchar(36) NOT NULL,
  escolaridade_do_aluno varchar(47),
  escolaridadecatalogoguia varchar(47),
  formaingresso varchar(22),
  instituicao varchar(14),
  mantenedora varchar(117),
  municipiodaue varchar(29) NOT NULL,
  municipiodolocaldaoferta varchar(33) NOT NULL,
  nodependenciaadmin varchar(22) NOT NULL,
  nomodalidade varchar(77),
  noparceirodemandante varchar(83) NOT NULL,
  noprograma varchar(151),
  nosistemaensino varchar(20) NOT NULL,
  nosubdependenciaadmin varchar(5),
  nome_aluno varchar(69),
  nome_da_sit_matricula__situacao_detalhada_ varchar(21),
  nomecursocatalogoguia varchar(94),
  nomedaue varchar(154) NOT NULL,
  nomedauer varchar(126) NOT NULL,
  nomedocurso varchar(94) NOT NULL,
  nutelefone varchar(14),
  nutelefonecelular varchar(14),
  ofertacadastroonline varchar(4) NOT NULL,
  pcd varchar(116) NOT NULL,
  populacaocampo varchar(113),
  povoindigena varchar(58),
  segurodesenprego varchar(3),
  sexo_do_aluno varchar(1),
  situacaodaturma varchar(10) NOT NULL,
  stextemporaneomatricula boolean,
  stextemporaneoturma boolean NOT NULL,
  stfinanciavel varchar(4) NOT NULL,
  subtipocurso varchar(21) NOT NULL,
  tipodaoferta varchar(13) NOT NULL,
  tipodolocaldaoferta varchar(3) NOT NULL,
  totalconffreqaluno varchar(2),
  totalfreqaluno smallint,
  transferenciarenda varchar(69) NOT NULL,
  turno varchar(6) NOT NULL,
  ufdaue varchar(2) NOT NULL,
  ufdolocaldaoferta varchar(2) NOT NULL,
  unidadedemandante varchar(151),
  vagas smallint NOT NULL,
  valorhoraaulaproposto varchar(5),
  calculation838513978982854656 varchar(117)
);
