create table nyc2(
  address_type varchar(12),
  agency_name varchar(91) NOT NULL,
  agency varchar(10) NOT NULL,
  borough varchar(13) NOT NULL,
  bridge_highway_direction varchar(30),
  bridge_highway_name varchar(42),
  bridge_highway_segment date,
  city varchar(32),
  closed_date timestamp,
  community_board varchar(25) NOT NULL,
  complaint_type varchar(41) NOT NULL,
  created_date timestamp NOT NULL,
  cross_street1 varchar(36),
  cross_street2 varchar(36),
  descriptor varchar(200),
  due_date timestamp,
  facility_type varchar(15),
  ferry_direction varchar(19),
  ferry_terminal_name varchar(95),
  garage_lot_name varchar(27),
  incident_address varchar(96),
  incident_zip bigint,
  intersection_street1 varchar(38),
  intersection_street2 varchar(47),
  landmark varchar(33),
  latitude decimal(15, 13),
  location_type varchar(36),
  location varchar(40),
  longitude decimal(15, 13),
  number_of_records smallint NOT NULL,
  park_borough varchar(13) NOT NULL,
  park_facility_name varchar(95) NOT NULL,
  resolution_action_updated_date timestamp,
  resolution_description varchar(500),
  road_ramp varchar(7),
  school_address varchar(120),
  school_city varchar(19) NOT NULL,
  school_code varchar(11),
  school_name varchar(95) NOT NULL,
  school_not_found varchar(1),
  school_number varchar(11),
  school_phone_number varchar(11) NOT NULL,
  school_region varchar(11),
  school_state varchar(11) NOT NULL,
  school_zip varchar(11) NOT NULL,
  school_or_citywide_complaint varchar(18),
  status varchar(28) NOT NULL,
  street_name varchar(96),
  taxi_company_borough varchar(13),
  taxi_pick_up_location varchar(27),
  unique_key integer NOT NULL,
  vehicle_type varchar(23),
  x_coordinate__state_plane_ integer,
  y_coordinate__state_plane_ integer
);
