SELECT COALESCE(SUM("t9"."EXPR$0" * "t10"."EXPR$0"), 0)
FROM (SELECT "t5"."userid", COALESCE(SUM("t5"."$f5" * "t7"."EXPR$0"), 0) AS "EXPR$0"
FROM (SELECT "t3"."userid", "t3"."id0", "t3"."$f5" * "t4"."EXPR$0" AS "$f5"
FROM (SELECT "t1"."userid", "t1"."id" AS "id0", "t1"."$f5" * "t2"."EXPR$0" AS "$f5"
FROM (SELECT "t"."userid", "t0"."id", "t"."EXPR$0" * "t0"."EXPR$0" AS "$f5"
FROM (SELECT "userid", "postid", COUNT(*) AS "EXPR$0"
FROM "comments"
GROUP BY "userid", "postid") AS "t"
INNER JOIN (SELECT "id", COUNT(*) AS "EXPR$0"
FROM "posts"
GROUP BY "id") AS "t0" ON "t"."postid" = "t0"."id") AS "t1"
INNER JOIN (SELECT "relatedpostid", COUNT(*) AS "EXPR$0"
FROM "postlinks"
GROUP BY "relatedpostid") AS "t2" ON "t1"."id" = "t2"."relatedpostid") AS "t3"
INNER JOIN (SELECT "postid", COUNT(*) AS "EXPR$0"
FROM "posthistory"
GROUP BY "postid") AS "t4" ON "t3"."id0" = "t4"."postid") AS "t5"
INNER JOIN (SELECT "postid", COUNT(*) AS "EXPR$0"
FROM "votes"
WHERE CAST("creationdate" AS TIMESTAMP(0)) >= TIMESTAMP '2010-07-19 00:00:00' AND CAST("creationdate" AS TIMESTAMP(0)) <= TIMESTAMP '2014-09-10 00:00:00'
GROUP BY "postid") AS "t7" ON "t5"."id0" = "t7"."postid"
GROUP BY "t5"."userid") AS "t9"
INNER JOIN (SELECT "userid", COUNT(*) AS "EXPR$0"
FROM "badges"
GROUP BY "userid") AS "t10" ON "t9"."userid" = "t10"."userid"