create table commongovernment4(
  number_of_records smallint NOT NULL,
  aaidacontidagencyid varchar(4) NOT NULL,
  aaidacontidpiid varchar(50) NOT NULL,
  agname varchar(50) NOT NULL,
  agencycode varchar(2) NOT NULL,
  aserowid integer NOT NULL,
  awardtype varchar(21) NOT NULL,
  awardtypecode varchar(1) NOT NULL,
  awardtypekey smallint NOT NULL,
  baseandalloptionsvalue DOUBLE PRECISION NOT NULL,
  baseandexercisedoptionsvalue DOUBLE PRECISION NOT NULL,
  bureaucode varchar(2) NOT NULL,
  bureauname varchar(40) NOT NULL,
  cdcontactiontype varchar(1),
  coname varchar(44),
  costate varchar(2),
  code varchar(2) NOT NULL,
  contractnum varchar(50),
  contractsigneddate varchar(20) NOT NULL,
  contractingofficeagencyid varchar(4) NOT NULL,
  countfetched integer NOT NULL,
  counttotal integer NOT NULL,
  description varchar(40) NOT NULL,
  fkepadesprod smallint,
  fkrecmat smallint,
  ftsdollar DOUBLE PRECISION NOT NULL,
  fundingagency varchar(4),
  fundingagencykey integer NOT NULL,
  fundingagencyname varchar(40) NOT NULL,
  gsadollar DOUBLE PRECISION NOT NULL,
  gsaotherdollar DOUBLE PRECISION NOT NULL,
  gwacs DOUBLE PRECISION NOT NULL,
  level1category varchar(37) NOT NULL,
  level2category varchar(57) NOT NULL,
  naicscode varchar(6) NOT NULL,
  naicsname varchar(35) NOT NULL,
  nongsadollar DOUBLE PRECISION NOT NULL,
  obligatedamount DOUBLE PRECISION NOT NULL,
  obligatedamount1 decimal(1, 0),
  pbsdollar DOUBLE PRECISION NOT NULL,
  primarycontractpiid varchar(51) NOT NULL,
  prodorservcode varchar(4) NOT NULL,
  prodorservcodedesc varchar(35),
  psccode varchar(4) NOT NULL,
  psccodedescription varchar(100) NOT NULL,
  psckey integer NOT NULL,
  quarter varchar(1) NOT NULL,
  refidvidagencyid varchar(4) NOT NULL,
  refidvidpiid varchar(34),
  shortname varchar(11) NOT NULL,
  signeddate varchar(19) NOT NULL,
  vendcontoffbussizedeterm varchar(1) NOT NULL,
  venddunsnumber varchar(9) NOT NULL,
  vendvendorname varchar(108),
  whocanuse varchar(50),
  year varchar(4) NOT NULL
);
