create table motos1(
  anunciante varchar(37),
  aviso varchar(19),
  a_o smallint NOT NULL,
  cadena varchar(22),
  categoria varchar(47) NOT NULL,
  circulacion varchar(21),
  codigo integer NOT NULL,
  cols smallint NOT NULL,
  concatenar1 varchar(54),
  concatenar2 varchar(76),
  corte smallint NOT NULL,
  denpags smallint,
  diasemana smallint NOT NULL,
  disco smallint,
  duracion smallint,
  est varchar(3),
  fecha date NOT NULL,
  franja varchar(25),
  genero varchar(17),
  holding varchar(7) NOT NULL,
  horapagina integer,
  inversionq DOUBLE PRECISION NOT NULL,
  inversionus DOUBLE PRECISION NOT NULL,
  marca varchar(37) NOT NULL,
  medio varchar(19) NOT NULL,
  mes varchar(7) NOT NULL,
  numanuncios smallint NOT NULL,
  number_of_records smallint NOT NULL,
  plgs smallint NOT NULL,
  posicionedicion smallint NOT NULL,
  primeralinea varchar(90),
  producto varchar(39) NOT NULL,
  semana smallint,
  sector varchar(40) NOT NULL,
  soporte varchar(84),
  subsector varchar(39) NOT NULL,
  unidad varchar(1),
  ver_anuncio varchar(54),
  vehiculo varchar(23) NOT NULL,
  extencion varchar(5),
  medio2 varchar(2),
  www1 varchar(31),
  www2 varchar(57),
  anunciante__grupo_ varchar(34)
);
