create table salariesfrance1(
  a129 varchar(4) NOT NULL,
  a129libcourt varchar(46) NOT NULL,
  a129libcourtpj varchar(40),
  a129lib varchar(162) NOT NULL,
  a88 varchar(2) NOT NULL,
  a88lib varchar(138) NOT NULL,
  adecconbcandidats decimal(4, 0),
  adecconbcandmetiersproches DOUBLE PRECISION,
  adeccosalairesbruts decimal(18, 14),
  ag2529 DOUBLE PRECISION,
  ag3039 DOUBLE PRECISION,
  ag4049 DOUBLE PRECISION,
  ag5054 DOUBLE PRECISION,
  agm25 DOUBLE PRECISION,
  agp55 DOUBLE PRECISION,
  apprenti DOUBLE PRECISION,
  bmodifficile DOUBLE PRECISION,
  bmointentions DOUBLE PRECISION,
  bmosaison DOUBLE PRECISION,
  codgeoprincipal varchar(5) NOT NULL,
  cpprincipal varchar(5),
  calculation163536984210948109 smallint NOT NULL,
  calculation392657618632466432 DOUBLE PRECISION,
  calculation393783518250995712 DOUBLE PRECISION,
  embauchesglobal DOUBLE PRECISION,
  embauchesnm1 DOUBLE PRECISION,
  embauchesnp1 DOUBLE PRECISION,
  embauchecdd DOUBLE PRECISION,
  embauchecdi DOUBLE PRECISION,
  empsalnm1 DOUBLE PRECISION,
  empsalnp1 DOUBLE PRECISION,
  femmes DOUBLE PRECISION,
  hommes DOUBLE PRECISION,
  interimnm1 DOUBLE PRECISION,
  interimnp1 DOUBLE PRECISION,
  libdom1 varchar(74),
  libdom2 varchar(77),
  libellesromebonneformation varchar(92),
  libromeminuscule varchar(95),
  latitude decimal(15, 13),
  longitude DOUBLE PRECISION,
  nbdepe smallint,
  nbets smallint,
  nompagesjaunes varchar(33) NOT NULL,
  number_of_records smallint NOT NULL,
  reglib varchar(27) NOT NULL,
  renseigne varchar(1) NOT NULL,
  repere1__copie_ smallint NOT NULL,
  rome varchar(5),
  romelib varchar(95),
  salairebrut DOUBLE PRECISION,
  salairevf DOUBLE PRECISION,
  tksiret smallint,
  uimmfamilles varchar(38),
  ze2010 varchar(4) NOT NULL,
  ze2010lib varchar(35) NOT NULL,
  calculation490892384732147714 varchar(46) NOT NULL
);
