create table taxpayer4(
  number_of_records smallint NOT NULL,
  averagemedicareallowedamt DOUBLE PRECISION,
  averagemedicarepaymentamt DOUBLE PRECISION,
  averagesubmittedchrgamt DOUBLE PRECISION,
  benedaysrvccnt integer,
  beneuniquecnt integer,
  hcpcscode integer,
  hcpcsdescription varchar(28),
  linesrvccnt integer,
  medicareparticipationindicator varchar(1),
  npi integer NOT NULL,
  nppescredentials varchar(20),
  nppesentitycode varchar(1),
  nppesprovidercity varchar(28),
  nppesprovidercountry varchar(2),
  nppesproviderfirstname varchar(20),
  nppesprovidergender varchar(1),
  nppesproviderlastorgname varchar(70),
  nppesprovidermi varchar(1),
  nppesproviderstate varchar(2),
  nppesproviderstreet1 varchar(55),
  nppesproviderstreet2 varchar(55),
  nppesproviderzip integer,
  placeofservice varchar(1),
  providertype varchar(43),
  stdevmedicareallowedamt DOUBLE PRECISION,
  stdevmedicarepaymentamt DOUBLE PRECISION,
  stdevsubmittedchrgamt DOUBLE PRECISION
);
