create table trainsuk22(
  actual_total_distance_miles decimal(5, 2),
  date timestamp,
  financial_year___period varchar(23),
  number_of_records smallint NOT NULL,
  operator varchar(8),
  planned_dest_actual_datetime timestamp,
  planned_dest_gbtt_datetime timestamp,
  planned_dest_stanox_description varchar(31),
  planned_dest_stanox integer,
  planned_dest_wtt_datetime timestamp,
  planned_orig_stanox_description varchar(31),
  planned_orig_stanox integer,
  planned_origin_actual_datetime timestamp,
  planned_origin_gbtt_datetime timestamp,
  planned_origin_wtt_datetime timestamp,
  planned_total_distance_miles decimal(5, 2),
  service_group_code varchar(18),
  service_group_description varchar(42),
  tsc integer,
  train_id varchar(10),
  vcasl_flag smallint NOT NULL,
  vdest_lateness__gbtt_ smallint,
  vdest_lateness__wtt_ decimal(4, 1),
  vfull_cancellation_flag smallint NOT NULL,
  vorigin_lateness__gbtt_ smallint,
  vorigin_lateness__wtt_ smallint,
  vppm_pass_flag smallint NOT NULL,
  vrt_flag smallint NOT NULL,
  vsector varchar(8),
  vunique_train_id varchar(24),
  corigin_time__gbtt___copy_ varchar(5),
  calculation2510610113130467 smallint,
  calculation4220604162631191 varchar(71),
  calculation5580608170646388 varchar(5),
  calculation6080608165132814 varchar(4),
  calculation9230610113105724 smallint,
  date__group_ timestamp
);
