create table uscensus3(
  access smallint,
  acr smallint,
  adjhsg integer NOT NULL,
  adjinc integer NOT NULL,
  adjinc1 integer NOT NULL,
  agep smallint NOT NULL,
  ags smallint,
  anc1p smallint NOT NULL,
  anc2p smallint NOT NULL,
  anc smallint NOT NULL,
  bath smallint,
  bdsp smallint,
  bld smallint,
  broadbnd smallint,
  bus smallint,
  citwp smallint,
  cit smallint NOT NULL,
  compothx smallint,
  conp smallint,
  cow smallint,
  ddrs smallint,
  dear smallint NOT NULL,
  decade smallint,
  deye smallint NOT NULL,
  dialup smallint,
  dis smallint NOT NULL,
  division smallint NOT NULL,
  dout smallint,
  dphy smallint,
  dratx smallint,
  drat smallint,
  drem smallint,
  drivesp smallint,
  dsl smallint,
  elep smallint,
  eng smallint,
  esp smallint,
  esr smallint,
  faccessp smallint,
  facrp smallint,
  fagep smallint NOT NULL,
  fagsp smallint,
  fancp smallint NOT NULL,
  fbathp smallint,
  fbdsp smallint,
  fbldp smallint,
  fbroadbndp smallint,
  fbusp smallint,
  fcitp smallint NOT NULL,
  fcitwp smallint NOT NULL,
  fcompothxp smallint,
  fconp smallint,
  fcowp smallint NOT NULL,
  fddrsp smallint NOT NULL,
  fdearp smallint NOT NULL,
  fdeyep smallint NOT NULL,
  fdialupp smallint,
  fdisp smallint NOT NULL,
  fdoutp smallint NOT NULL,
  fdphyp smallint NOT NULL,
  fdratp smallint NOT NULL,
  fdratxp smallint NOT NULL,
  fdremp smallint NOT NULL,
  fdslp smallint,
  felep smallint,
  fengp smallint NOT NULL,
  fer smallint,
  fesrp smallint NOT NULL,
  fes smallint,
  fferp smallint NOT NULL,
  ffiberopp smallint,
  ffincp smallint,
  ffodp smallint NOT NULL,
  ffsp smallint NOT NULL,
  ffulp smallint,
  fgasp smallint,
  fgclp smallint NOT NULL,
  fgcmp smallint NOT NULL,
  fgcrp smallint NOT NULL,
  fgrntp smallint,
  fhandheldp smallint,
  fhflp smallint,
  fhincp smallint,
  fhins1p smallint NOT NULL,
  fhins2p smallint NOT NULL,
  fhins3c smallint,
  fhins3p smallint NOT NULL,
  fhins4c smallint,
  fhins4p smallint NOT NULL,
  fhins5c smallint,
  fhins5p smallint NOT NULL,
  fhins6p smallint NOT NULL,
  fhins7p smallint NOT NULL,
  fhisp smallint NOT NULL,
  fiberop smallint,
  fincp integer,
  findp smallint NOT NULL,
  finsp smallint,
  fintp smallint NOT NULL,
  fjwdp smallint NOT NULL,
  fjwmnp smallint NOT NULL,
  fjwrip smallint NOT NULL,
  fjwtrp smallint NOT NULL,
  fkitp smallint,
  flanp smallint NOT NULL,
  flanxp smallint NOT NULL,
  flaptopp smallint,
  fmarhdp smallint NOT NULL,
  fmarhmp smallint NOT NULL,
  fmarhtp smallint NOT NULL,
  fmarhwp smallint NOT NULL,
  fmarhyp smallint NOT NULL,
  fmarp smallint NOT NULL,
  fmhp smallint,
  fmigp smallint NOT NULL,
  fmigsp smallint NOT NULL,
  fmilpp smallint NOT NULL,
  fmilsp smallint NOT NULL,
  fmodemp smallint,
  fmrgip smallint,
  fmrgp smallint,
  fmrgtp smallint,
  fmrgxp smallint,
  fmvp smallint NOT NULL,
  foccp smallint NOT NULL,
  fod1p smallint,
  fod2p smallint,
  foip smallint NOT NULL,
  fothsvcexp smallint,
  fpap smallint NOT NULL,
  fparc smallint,
  fpernp smallint NOT NULL,
  fpincp smallint NOT NULL,
  fplmp smallint,
  fpobp smallint NOT NULL,
  fpowsp smallint NOT NULL,
  fprivcovp smallint NOT NULL,
  fpubcovp smallint NOT NULL,
  fracp smallint NOT NULL,
  frefrp smallint,
  frelp smallint NOT NULL,
  fretp smallint NOT NULL,
  frmsp smallint,
  frntmp smallint,
  frntp smallint,
  frwatprp smallint,
  frwatp smallint,
  fsatellitep smallint,
  fschgp smallint NOT NULL,
  fschlp smallint NOT NULL,
  fschp smallint NOT NULL,
  fsemp smallint NOT NULL,
  fsexp smallint NOT NULL,
  fsinkp smallint,
  fsmocp smallint,
  fsmp smallint,
  fsmxhp smallint,
  fsmxsp smallint,
  fssip smallint NOT NULL,
  fssp smallint NOT NULL,
  fstovp smallint,
  fs smallint NOT NULL,
  ftaxp smallint,
  ftelp smallint,
  ftenp smallint,
  ftoilp smallint,
  fulp smallint,
  fvacsp smallint,
  fvalp smallint,
  fvehp smallint,
  fwagp smallint NOT NULL,
  fwatp smallint,
  fwkhp smallint NOT NULL,
  fwklp smallint NOT NULL,
  fwkwp smallint NOT NULL,
  fwrkp smallint NOT NULL,
  fyblp smallint,
  fyoep smallint NOT NULL,
  gasp smallint,
  gcl smallint,
  gcm smallint,
  gcr smallint,
  grntp smallint,
  grpip smallint,
  handheld smallint,
  hfl smallint,
  hhl smallint,
  hht smallint,
  hicov smallint NOT NULL,
  hincp integer,
  hins1 smallint NOT NULL,
  hins2 smallint NOT NULL,
  hins3 smallint NOT NULL,
  hins4 smallint NOT NULL,
  hins5 smallint NOT NULL,
  hins6 smallint NOT NULL,
  hins7 smallint NOT NULL,
  hisp smallint NOT NULL,
  hugcl smallint,
  hupac smallint,
  hupaoc smallint,
  huparc smallint,
  indp smallint,
  insp smallint,
  intp integer,
  jwap smallint,
  jwdp smallint,
  jwmnp smallint,
  jwrip smallint,
  jwtr smallint,
  kit smallint,
  lanp smallint,
  lanx smallint,
  laptop smallint,
  lngi smallint,
  marhd smallint,
  marhm smallint,
  marht smallint,
  marhw smallint,
  marhyp smallint,
  mar smallint NOT NULL,
  mhp smallint,
  migpuma integer,
  migsp smallint,
  mig smallint,
  mil smallint,
  mlpa smallint,
  mlpb smallint,
  mlpcd smallint,
  mlpe smallint,
  mlpfg smallint,
  mlph smallint,
  mlpi smallint,
  mlpj smallint,
  mlpk smallint,
  modem smallint,
  mrgi smallint,
  mrgp smallint,
  mrgt smallint,
  mrgx smallint,
  msp smallint,
  multg smallint,
  mv smallint,
  naicsp varchar(8),
  nativity smallint NOT NULL,
  noc smallint,
  nop smallint,
  npf smallint,
  npp smallint,
  np smallint NOT NULL,
  nrc smallint,
  nr smallint,
  nwab smallint,
  nwav smallint,
  nwla smallint,
  nwlk smallint,
  nwre smallint,
  number_of_records smallint NOT NULL,
  occp smallint,
  ocpip smallint,
  oc smallint NOT NULL,
  oip integer,
  othsvcex smallint,
  paoc smallint,
  pap smallint,
  partner smallint,
  pernp integer,
  pincp integer,
  plm smallint,
  pobp smallint NOT NULL,
  povpip smallint,
  powpuma integer,
  powsp smallint,
  privcov smallint NOT NULL,
  psf smallint,
  pubcov smallint NOT NULL,
  puma integer NOT NULL,
  puma1 integer NOT NULL,
  pwgtp smallint NOT NULL,
  qtrbir smallint NOT NULL,
  r18 smallint,
  r60 smallint,
  r65 smallint,
  rac1p smallint NOT NULL,
  rac2p smallint NOT NULL,
  rac3p smallint NOT NULL,
  racaian smallint NOT NULL,
  racasn smallint NOT NULL,
  racblk smallint NOT NULL,
  racnh smallint NOT NULL,
  racnum smallint NOT NULL,
  racpi smallint NOT NULL,
  racsor smallint NOT NULL,
  racwht smallint NOT NULL,
  rc smallint NOT NULL,
  refr smallint,
  region smallint NOT NULL,
  relp smallint NOT NULL,
  resmode smallint,
  retp integer,
  rmsp smallint,
  rntm smallint,
  rntp smallint,
  rt varchar(1) NOT NULL,
  rt1 varchar(1) NOT NULL,
  rwatpr smallint,
  rwat smallint,
  satellite smallint,
  schg smallint,
  schl smallint,
  sch smallint,
  sciengp smallint,
  sciengrlp smallint,
  semp integer,
  serialno integer NOT NULL,
  serialno1 integer NOT NULL,
  sex smallint NOT NULL,
  sfn smallint,
  sfr smallint,
  sink smallint,
  smocp smallint,
  smp smallint,
  smx smallint,
  socp varchar(6),
  sporder smallint NOT NULL,
  srnt smallint,
  ssip smallint,
  ssmc smallint,
  ssp integer,
  st smallint NOT NULL,
  stov smallint,
  st1 smallint NOT NULL,
  sval smallint,
  taxp smallint,
  tel smallint,
  ten smallint,
  toil smallint,
  type smallint NOT NULL,
  table_name varchar(12) NOT NULL,
  table_name1 varchar(12) NOT NULL,
  vacs bigint,
  valp integer,
  veh smallint,
  vps smallint,
  wagp integer,
  waob smallint NOT NULL,
  watp smallint,
  wgtp smallint NOT NULL,
  wif smallint,
  wkexrel smallint,
  wkhp smallint,
  wkl smallint,
  wkw smallint,
  workstat smallint,
  wrk smallint,
  ybl smallint,
  yoep smallint,
  pwgtp10 smallint NOT NULL,
  pwgtp11 smallint NOT NULL,
  pwgtp12 smallint NOT NULL,
  pwgtp13 smallint NOT NULL,
  pwgtp14 smallint NOT NULL,
  pwgtp15 smallint NOT NULL,
  pwgtp16 smallint NOT NULL,
  pwgtp17 smallint NOT NULL,
  pwgtp18 smallint NOT NULL,
  pwgtp19 smallint NOT NULL,
  pwgtp1 smallint NOT NULL,
  pwgtp20 smallint NOT NULL,
  pwgtp21 smallint NOT NULL,
  pwgtp22 smallint NOT NULL,
  pwgtp23 smallint NOT NULL,
  pwgtp24 smallint NOT NULL,
  pwgtp25 smallint NOT NULL,
  pwgtp26 smallint NOT NULL,
  pwgtp27 smallint NOT NULL,
  pwgtp28 smallint NOT NULL,
  pwgtp29 smallint NOT NULL,
  pwgtp2 smallint NOT NULL,
  pwgtp30 smallint NOT NULL,
  pwgtp31 smallint NOT NULL,
  pwgtp32 smallint NOT NULL,
  pwgtp33 smallint NOT NULL,
  pwgtp34 smallint NOT NULL,
  pwgtp35 smallint NOT NULL,
  pwgtp36 smallint NOT NULL,
  pwgtp37 smallint NOT NULL,
  pwgtp38 smallint NOT NULL,
  pwgtp39 smallint NOT NULL,
  pwgtp3 smallint NOT NULL,
  pwgtp40 smallint NOT NULL,
  pwgtp41 smallint NOT NULL,
  pwgtp42 smallint NOT NULL,
  pwgtp43 smallint NOT NULL,
  pwgtp44 smallint NOT NULL,
  pwgtp45 smallint NOT NULL,
  pwgtp46 smallint NOT NULL,
  pwgtp47 smallint NOT NULL,
  pwgtp48 smallint NOT NULL,
  pwgtp49 smallint NOT NULL,
  pwgtp4 smallint NOT NULL,
  pwgtp50 smallint NOT NULL,
  pwgtp51 smallint NOT NULL,
  pwgtp52 smallint NOT NULL,
  pwgtp53 smallint NOT NULL,
  pwgtp54 smallint NOT NULL,
  pwgtp55 smallint NOT NULL,
  pwgtp56 smallint NOT NULL,
  pwgtp57 smallint NOT NULL,
  pwgtp58 smallint NOT NULL,
  pwgtp59 smallint NOT NULL,
  pwgtp5 smallint NOT NULL,
  pwgtp60 smallint NOT NULL,
  pwgtp61 smallint NOT NULL,
  pwgtp62 smallint NOT NULL,
  pwgtp63 smallint NOT NULL,
  pwgtp64 smallint NOT NULL,
  pwgtp65 smallint NOT NULL,
  pwgtp66 smallint NOT NULL,
  pwgtp67 smallint NOT NULL,
  pwgtp68 smallint NOT NULL,
  pwgtp69 smallint NOT NULL,
  pwgtp6 smallint NOT NULL,
  pwgtp70 smallint NOT NULL,
  pwgtp71 smallint NOT NULL,
  pwgtp72 smallint NOT NULL,
  pwgtp73 smallint NOT NULL,
  pwgtp74 smallint NOT NULL,
  pwgtp75 smallint NOT NULL,
  pwgtp76 smallint NOT NULL,
  pwgtp77 smallint NOT NULL,
  pwgtp78 smallint NOT NULL,
  pwgtp79 smallint NOT NULL,
  pwgtp7 smallint NOT NULL,
  pwgtp80 smallint NOT NULL,
  pwgtp8 smallint NOT NULL,
  pwgtp9 smallint NOT NULL,
  wgtp10 smallint NOT NULL,
  wgtp11 smallint NOT NULL,
  wgtp12 smallint NOT NULL,
  wgtp13 smallint NOT NULL,
  wgtp14 smallint NOT NULL,
  wgtp15 smallint NOT NULL,
  wgtp16 smallint NOT NULL,
  wgtp17 smallint NOT NULL,
  wgtp18 smallint NOT NULL,
  wgtp19 smallint NOT NULL,
  wgtp1 smallint NOT NULL,
  wgtp20 smallint NOT NULL,
  wgtp21 smallint NOT NULL,
  wgtp22 smallint NOT NULL,
  wgtp23 smallint NOT NULL,
  wgtp24 smallint NOT NULL,
  wgtp25 smallint NOT NULL,
  wgtp26 smallint NOT NULL,
  wgtp27 smallint NOT NULL,
  wgtp28 smallint NOT NULL,
  wgtp29 smallint NOT NULL,
  wgtp2 smallint NOT NULL,
  wgtp30 smallint NOT NULL,
  wgtp31 smallint NOT NULL,
  wgtp32 smallint NOT NULL,
  wgtp33 smallint NOT NULL,
  wgtp34 smallint NOT NULL,
  wgtp35 smallint NOT NULL,
  wgtp36 smallint NOT NULL,
  wgtp37 smallint NOT NULL,
  wgtp38 smallint NOT NULL,
  wgtp39 smallint NOT NULL,
  wgtp3 smallint NOT NULL,
  wgtp40 smallint NOT NULL,
  wgtp41 smallint NOT NULL,
  wgtp42 smallint NOT NULL,
  wgtp43 smallint NOT NULL,
  wgtp44 smallint NOT NULL,
  wgtp45 smallint NOT NULL,
  wgtp46 smallint NOT NULL,
  wgtp47 smallint NOT NULL,
  wgtp48 smallint NOT NULL,
  wgtp49 smallint NOT NULL,
  wgtp4 smallint NOT NULL,
  wgtp50 smallint NOT NULL,
  wgtp51 smallint NOT NULL,
  wgtp52 smallint NOT NULL,
  wgtp53 smallint NOT NULL,
  wgtp54 smallint NOT NULL,
  wgtp55 smallint NOT NULL,
  wgtp56 smallint NOT NULL,
  wgtp57 smallint NOT NULL,
  wgtp58 smallint NOT NULL,
  wgtp59 smallint NOT NULL,
  wgtp5 smallint NOT NULL,
  wgtp60 smallint NOT NULL,
  wgtp61 smallint NOT NULL,
  wgtp62 smallint NOT NULL,
  wgtp63 smallint NOT NULL,
  wgtp64 smallint NOT NULL,
  wgtp65 smallint NOT NULL,
  wgtp66 smallint NOT NULL,
  wgtp67 smallint NOT NULL,
  wgtp68 smallint NOT NULL,
  wgtp69 smallint NOT NULL,
  wgtp6 smallint NOT NULL,
  wgtp70 smallint NOT NULL,
  wgtp71 smallint NOT NULL,
  wgtp72 smallint NOT NULL,
  wgtp73 smallint NOT NULL,
  wgtp74 smallint NOT NULL,
  wgtp75 smallint NOT NULL,
  wgtp76 smallint NOT NULL,
  wgtp77 smallint NOT NULL,
  wgtp78 smallint NOT NULL,
  wgtp79 smallint NOT NULL,
  wgtp7 smallint NOT NULL,
  wgtp80 smallint NOT NULL,
  wgtp8 smallint NOT NULL,
  wgtp9 smallint NOT NULL,
  wagp__bin_ smallint,
  agep__bin_ smallint NOT NULL
);
